version: '3.8'
services:
  gideon-studio:
    build:
      context: .
      args:
        FEATURE_FLAGS: "-market"
    ports:
      - "3000:3210"
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    environment:
      - NODE_ENV=production
      # Gideon Studio Branding
      - NEXT_PUBLIC_APP_NAME=Gideon Studio
      - NEXT_PUBLIC_APP_DESCRIPTION=Your Personal AI Studio
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://ai.gideon.studio}
      # Feature Flags - Disable Discover/Market
      - FEATURE_FLAGS=-market
      # Database
      - NEXT_PUBLIC_SERVICE_MODE=server
      - DATABASE_DRIVER=node
      - DATABASE_URL=${DATABASE_URL:-postgresql://gideon:password@postgres:5432/gideon_studio}
      # Authentication - Use deployment URL from .env.local
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - APP_URL=${APP_URL:-http://localhost:3000}
      - NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET:-create-a-secure-secret}
      - KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET:-create-a-secure-key}
      # Google Gemini (set your API key here)
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-your-google-gemini-api-key}
      # ChromaDB Connection
      - CHROMADB_URL=http://chromadb:8000
      # Additional LLMs (optional)
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - chromadb

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: gideon_studio
      POSTGRES_USER: gideon
      POSTGRES_PASSWORD: password
    volumes:
      - /home/jaymes/postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gideon -d gideon_studio"]
      interval: 30s
      timeout: 10s
      retries: 5

  chromadb:
    image: chromadb/chroma:latest
    container_name: gideon-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      # Development auth (configure for production)
      - CHROMA_SERVER_AUTHN_CREDENTIALS=admin:chromadb_password
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token_authn.TokenAuthenticationServerProvider
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chromadb_data:
